version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: ./Docker/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/react-app
  prod:
    build:
      context: .
      dockerfile: ./Docker/prod/Dockerfile
    ports:
      - "3001:3000"
